spring:
  profiles:
    active:
      - test
  cloud:
    config:
      server:
        git:
          uri: git@github.com:fypshencheng/spring-cloud-congfig-server-demo.git
server:
  port: 9090
---
spring:
 profiles: dev
 application:
  name: config-server-dev
---
spring:
 profiles: test
 application:
  name: config-server-test
